In [1]:
#import packages
import pandas as pd
import numpy as np
import datetime
import scipy
from scipy import stats
from scipy.optimize import curve_fit

In [4]:
#I#SOTOPE DATA##
#read in isotope data and turn it into pandas dataframe
SG_water=pd.read_csv('/path/to/dataset/PWFH_code/datasets/SanGabes_WaterIsotopeData.csv')
df=pd.DataFrame(SG_water)

#set timestamp, calculate d-excess, group data by sample type, streams and storm number
df['timestamp']=df['Date']+' '+df['Time']
df['date_time']=pd.to_datetime(df['timestamp'])
df['d-excess']=df['𝛿D']-8*df['𝛿18O']
streams=df.loc[df['Sample Type'] == 'Stream']
rain=df.loc[df['Sample Type'] == 'Rain']
intrain=df.loc[df['Sample Type'] == 'Integrated Rain']
storm1=df.loc[df['Storm'] =='storm 1']
storm2=df.loc[df['Storm'] =='storm 2']
storm3=df.loc[df['Storm'] =='storm 3']
storm4=df.loc[df['Storm'] =='storm 4']
storm5=df.loc[df['Storm'] =='storm 5']
storm6=df.loc[df['Storm'] =='storm 6']
storm7=df.loc[df['Storm'] =='storm 7']
df_sorted=df.sort_values(by='date_time')

#make custom color map by location
colors=['#F26513','#F2921D', '#019966' ]
locations=['Louise','Thelma', 'Henry']
cmap=dict(zip(locations, colors))

In [15]:
##RAINFALL DATA##
#read in rainfall data and turn it into pandas dataframe
precip=pd.read_csv('/path/to/dataset/PWFH_code/datasets/Bobat_Fire_Rain_Gauge_Dec2020_May2022.csv')
precip=pd.DataFrame(precip)

#set date time and other titles
precip['date_time']=pd.to_datetime(precip['Date and Time'])
precip['rain_units']=precip['Rainfall units']
precip['cum_rain_cm']=precip['Cumulative Rainfall  (cm) ']
precip['rain_cm']=precip['Rainfall (cm)']
precip=precip.set_index('date_time')

In [16]:
#calculate average precipitation weighted isotopic value for each storm
storm1['weightediso']=(storm1['𝛿18O']*storm1['Rain (cm)'])/(storm1['Rain (cm)'].sum())
s1pw18O=storm1['weightediso'].sum()
storm2['weightediso']=(storm2['𝛿18O']*storm2['Rain (cm)'])/(storm2['Rain (cm)'].sum())
s2pw18O=storm2['weightediso'].sum()
storm3['weightediso']=(storm3['𝛿18O']*storm3['Rain (cm)'])/(storm3['Rain (cm)'].sum())
s3pw18O=storm3['weightediso'].sum()
storm4['weightediso']=(storm4['𝛿18O']*storm4['Rain (cm)'])/(storm4['Rain (cm)'].sum())
s4pw18O=storm4['weightediso'].sum()
storm5['weightediso']=(storm5['𝛿18O']*storm5['Rain (cm)'])/(storm5['Rain (cm)'].sum())
s5pw18O=storm5['weightediso'].sum()
storm6['weightediso']=(storm6['𝛿18O']*storm6['Rain (cm)'])/(storm6['Rain (cm)'].sum())
s6pw18O=storm6['weightediso'].sum()
storm7['weightediso']=(storm7['𝛿18O']*storm7['Rain (cm)'])/(storm7['Rain (cm)'].sum())
s7pw18O=storm7['weightediso'].sum()

/var/folders/14/ghgmys9n68bgp8t79gqjtc4w0000gn/T/ipykernel_45205/2416385715.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  storm1['weightediso']=(storm1['𝛿18O']*storm1['Rain (cm)'])/(storm1['Rain (cm)'].sum())
/var/folders/14/ghgmys9n68bgp8t79gqjtc4w0000gn/T/ipykernel_45205/2416385715.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  storm2['weightediso']=(storm2['𝛿18O']*storm2['Rain (cm)'])/(storm2['Rain (cm)'].sum())
/var/folders/14/ghgmys9n68bgp8t79gqjtc4w0000gn/T/ipykernel_45205/2416385715.py:6: 

In [17]:
##Calculate relationship between rainfall intensity, Fnew and Kfs values##

In [18]:
##Fnew## 
#resample rainfall data for every 30 minutes, change units to mm/hr and find log rainfall
precip_30=pd.DataFrame()
precip_30['rain_cm']=precip.rain_cm.resample('30min', closed="left", label='right', origin='start').sum()
precip_30['rain_mm']=precip_30['rain_cm']*10
precip_30['rain_mmhr']=precip_30['rain_mm']*4
precip_30['rain_mmhr']=precip_30['rain_mmhr'].replace(0,np.nan)
precip_30['log_rain_mmhr']=  np.log10(precip_30['rain_mmhr'])


In [19]:
##read in fnew isotope data, add timstamp and locate storms with Fnew values ##
fnew=pd.read_csv('/path/to/dataset/PWFH_code/datasets/SanGabes_Fnew_isotopes.csv')
fnew['timestamp']=fnew['Date']+' '+fnew['Time']
fnew['date_time']=pd.to_datetime(fnew['timestamp'])
fnew=fnew.set_index('date_time')
storm4_fnew=fnew.loc['2021-12-14':'2021-12-15']
storm4_fnew=storm4_fnew.sort_values(by='date_time')
storm5_fnew=fnew.loc['2021-12-23':'2021-12-24']
storm5_fnew=storm5_fnew.sort_values(by='date_time')

/var/folders/14/ghgmys9n68bgp8t79gqjtc4w0000gn/T/ipykernel_45205/2302232642.py:6: FutureWarning: Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is deprecated and will raise a KeyError in a future Version.
  storm4_fnew=fnew.loc['2021-12-14':'2021-12-15']
/var/folders/14/ghgmys9n68bgp8t79gqjtc4w0000gn/T/ipykernel_45205/2302232642.py:8: FutureWarning: Value based partial slicing on non-monotonic DatetimeIndexes with non-existing keys is deprecated and will raise a KeyError in a future Version.
  storm5_fnew=fnew.loc['2021-12-23':'2021-12-24']


In [20]:
##Kfs Values ##
#read in Kfs values
SG_Ks=pd.read_csv('/path/to/dataset/PWFH_code/datasets/Kfs_results.csv')
Ks=pd.DataFrame(SG_Ks)

##replace 0 infiltration with extremely low infiltration rate for log conversion 
Ks.replace(0,0.000001,inplace=True)

#drop values higher than 3 standard deviation based on z-score
z = np.abs(stats.zscore(Ks['Ks (mm/hr)']))
print(np.where(z>3))
Ks=Ks.drop([25])
#calculate log of Ks values
Ks['log_ks_mmhr']= np.log10(Ks['Ks (mm/hr)'])
z = np.abs(stats.zscore(Ks['log_ks_mmhr']))
print(np.where(z > 3))

#separate data by catchment
henry=Ks.loc[Ks['Location']== 'Henry']
louise=Ks.loc[Ks['Location']== 'Louise']
thelma=Ks.loc[Ks['Location']== 'Thelma']
#find median log kfs values in mm/hr
HKfs=henry['log_ks_mmhr'].median()
LKfs=louise['log_ks_mmhr'].median()

#calculate the 30 min precipitation intensity devided by the median log kfs value at each catchment
precip_30['rain_intens/Lkfs']= precip_30['log_rain_mmhr']/LKfs
precip_30['rain_intens/Hkfs']= precip_30['log_rain_mmhr']/HKfs

#locate 30minute precip data for storms with calculable Fnew values  
storm4_precip=precip_30.loc['2021-12-14':'2021-12-15']
storm5_precip=precip_30.loc['2021-12-23':'2021-12-24']

(array([25]),)
(array([ 0,  1, 25, 27, 34]),)


In [21]:
#merge storm precipitation and storm fnew value based on date time
#for storm 4
merged=pd.merge_asof(storm4_fnew, storm4_precip, on="date_time", direction="nearest")
louise_merged=merged.loc[merged['Location'] =='Louise']
henry_merged=merged.loc[merged['Location'] =='Henry']
#for storm 5
merged2=pd.merge_asof(storm5_fnew, storm5_precip, on="date_time", direction="nearest")
louise_merged2=merged2.loc[merged2['Location'] =='Louise']
henry_merged2=merged2.loc[merged2['Location'] =='Henry']
#drop any non number values from the four datasets
henry_merged2=henry_merged2.dropna()
louise_merged2=louise_merged2.dropna()
henry_merged=henry_merged.dropna()
louise_merged=louise_merged.dropna()
#combine locational datasets
louise=pd.concat([louise_merged,  louise_merged2])
henry=pd.concat([henry_merged, henry_merged2])
#drop outliers
merged=pd.concat([louise, henry])
z = np.abs(stats.zscore(merged['Fnew']))
print(np.where(z > 3))
merged.drop(merged.index[[37, 48, 49, 52]], inplace=True)

#separate datasets by location after droping outliers
henry_merged=merged.loc[merged['Location'] =='Henry']
louise_merged=merged.loc[merged['Location'] =='Louise']
louise_merged['Kfs_reg']=louise_merged['rain_intens/Lkfs']
henry_merged['Kfs_reg']=henry_merged['rain_intens/Hkfs']
merged=pd.concat([louise_merged, henry_merged])


(array([37, 48, 49, 52]),)


/var/folders/14/ghgmys9n68bgp8t79gqjtc4w0000gn/T/ipykernel_45205/1874414420.py:27: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  louise_merged['Kfs_reg']=louise_merged['rain_intens/Lkfs']
/var/folders/14/ghgmys9n68bgp8t79gqjtc4w0000gn/T/ipykernel_45205/1874414420.py:28: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  henry_merged['Kfs_reg']=henry_merged['rain_intens/Hkfs']


In [22]:
# calculate function to fit for linear regression:
def fit_func(x, m, b):
    return (m*x) + b

In [24]:
# calculate linear regression of rainfall intenisty/kfs vs Fnew
# model fit on full sample of data:
Fpars, Fcov = curve_fit(f=fit_func, xdata=merged['Kfs_reg'], ydata=merged['Fnew']) 

# fitted plot values (for CI)
x_fitted = (merged['Kfs_reg'])
y_fitted = fit_func(x_fitted, *Fpars)

residuals=(merged['Fnew']-y_fitted)
ss_res=np.sum(residuals**2)
ss_tot=np.sum((merged['Fnew']-np.mean(merged['Fnew']))**2)
r_squared=1-(ss_res/ss_tot)
print(r_squared)

0.15089376379382047
